/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TokenExpiredImport } from './routes/tokenExpired'

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const TokenExpiredRoute = TokenExpiredImport.update({
  id: '/tokenExpired',
  path: '/tokenExpired',
  getParentRoute: () => rootRoute
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tokenExpired': {
      id: '/tokenExpired'
      path: '/tokenExpired'
      fullPath: '/tokenExpired'
      preLoaderRoute: typeof TokenExpiredImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tokenExpired': typeof TokenExpiredRoute
}

interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tokenExpired': typeof TokenExpiredRoute
}

interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tokenExpired': typeof TokenExpiredRoute
}

interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tokenExpired'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tokenExpired'
  id: '__root__' | '/' | '/tokenExpired'
  fileRoutesById: FileRoutesById
}

interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TokenExpiredRoute: typeof TokenExpiredRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokenExpiredRoute: TokenExpiredRoute
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
